# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
   - 2.11.7

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - slavaschmidt@gmx.de
jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

after_success:
  - codecov